[workspace]
resolver = "2"
members = ["projects/*"]
default-members = [
    "projects/tree-layout",
    "projects/ygg-viewer",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
